/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabla: typeof import('./src/components/Tabla.vue')['default']
    Tarjetas: typeof import('./src/components/Tarjetas.vue')['default']
    Texto: typeof import('./src/components/Texto.vue')['default']
    Titulo: typeof import('./src/components/Titulo.vue')['default']
  }
}
